AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Lambda Layer providing sharp with HEIC support

Parameters:
  OrganizationId:
    Default: none
    Description: With the principal set to *, grant permission to all accounts in the specified organization.
    Type: String
  Principal:
    Default: account
    Description: An account ID, or * to grant permission to use the layer to all AWS accounts.
    Type: String
  LayerName:
    Default: sharp-heic-kvazaar
    Description: The name of the Lambda Layer that will be created.
    Type: String

Conditions:
  NoOrganizationId: !Equals [ !Ref OrganizationId, none ]
  UseDefaultPrincipal: !Equals [ !Ref Principal, account ]

Resources:
  SharpHEICKvazaarLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Ref LayerName
      Description: Sharp Layer with HEIC Kvazaar Support
      ContentUri: ./layer/
      CompatibleRuntimes:
        - nodejs20.x
      LicenseInfo: 'MIT'
      RetentionPolicy: Retain
    Metadata:
      BuildMethod: makefile

  SharpHEICKvazaarLayerPermission:
    Type: AWS::Lambda::LayerVersionPermission
    Properties:
      Action: lambda:GetLayerVersion
      LayerVersionArn: !Ref SharpHEICKvazaarLayer
      Principal:
        Fn::If:
          - UseDefaultPrincipal
          - !Ref AWS::AccountId
          - !Ref Principal
      OrganizationId:
        Fn::If:
          - NoOrganizationId
          - !Ref AWS::NoValue
          - !Ref OrganizationId

Outputs:
  SharpHEICKavazaarLayerArn:
    Value: !Ref SharpHEICKvazaarLayer
    Description: ARN of the Sharp HEIC Lambda Layer
    Export:
      Name: SharpHEICKvazaarLayerArn
