AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Sample Lambda function using the sharp-heic lambda layer

Resources:
  SharpTestFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/
      Handler: index.handler
      Runtime: nodejs20.x
      Timeout: 10
      MemorySize: 1024
      Layers:
        - !ImportValue SharpHEICKvazaarLayerArn
